// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApn-b5lX0yX0VHOSkenY7GtmSpkkO9_38',
    appId: '1:519873449870:web:ae6f18248e7672549e5edf',
    messagingSenderId: '519873449870',
    projectId: 'reading-station-d0b53',
    authDomain: 'reading-station-d0b53.firebaseapp.com',
    storageBucket: 'reading-station-d0b53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOgB_NgCf9Zt7s_04PupJkUW87VD4Aesg',
    appId: '1:519873449870:android:738e72be0a5338799e5edf',
    messagingSenderId: '519873449870',
    projectId: 'reading-station-d0b53',
    storageBucket: 'reading-station-d0b53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGB6UOIFrF2AOXUilMhgsmdm5Lk9KCQSo',
    appId: '1:519873449870:ios:bf6943eb08ae2fc69e5edf',
    messagingSenderId: '519873449870',
    projectId: 'reading-station-d0b53',
    storageBucket: 'reading-station-d0b53.firebasestorage.app',
    iosBundleId: 'com.example.readingBookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGB6UOIFrF2AOXUilMhgsmdm5Lk9KCQSo',
    appId: '1:519873449870:ios:bf6943eb08ae2fc69e5edf',
    messagingSenderId: '519873449870',
    projectId: 'reading-station-d0b53',
    storageBucket: 'reading-station-d0b53.firebasestorage.app',
    iosBundleId: 'com.example.readingBookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApn-b5lX0yX0VHOSkenY7GtmSpkkO9_38',
    appId: '1:519873449870:web:469e7aca9f4ec5d79e5edf',
    messagingSenderId: '519873449870',
    projectId: 'reading-station-d0b53',
    authDomain: 'reading-station-d0b53.firebaseapp.com',
    storageBucket: 'reading-station-d0b53.firebasestorage.app',
  );

}